version: '3.3'
services:
  app:
    image: app
    ports:
    - "8080:8080"
    depends_on:
    - mypostgres-container
  mypostgres-container:
    image: postgres
    ports:
     - "5432:5432"
    environment:
     - POSTGRES_PASSWORD=password
     - POSTGRES_USER=postgres
     - POSTGRES_DB=mydb


